name: dmrkt

services:
  # INFRA
  anvil:
    image: ghcr.io/foundry-rs/foundry
    entrypoint: ["anvil"]
    command:
      - --fork-url=${MAINNET_RPC}
      - --chain-id=31337
      - --host=0.0.0.0
      - --port=8545
      - --fork-block-number=${FORK_START_BLOCK}
      - --mnemonic=${PARTICIPANT_MNEMONIC}
      - --accounts=1 # pipeline equally distributes between participants
      - --quiet
    ports:
      - "8545:8545"
    healthcheck:
      test:
        ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 10s

  mongo:
    image: mongo:7
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"

  # DMRKT COMPONENTS
  sim:
    image: ghcr.io/izcm/market-sim:v0.2.0
    entrypoint: [
        "bash",
        "-c",
        "echo '✔ Anvil up' && make pipeline P_SIZE=${PARTICIPANT_SIZE} \
        EPOCH_COUNT=${EPOCH_COUNT} EPOCH_SIZE=${EPOCH_SIZE} EXPORT_FLAG=--export \
        2>&1 | tee >(sed --unbuffered 's/\\x1b\\[[0-9;]*m//g' > /app/devtools/data/31337/sim.log)",
      ]
    volumes:
      # config files + env
      - ./config/sim/pipeline.toml:/app/devtools/pipeline.toml:rw
      - ./env.example/sim.env:/app/devtools/.env:ro
      # broadcst logs, tx request objects & pipeline logs
      - ./out/broadcast:/app/devtools/broadcast:rw
      - ./out/tx-out:/app/devtools/data/31337/state/tx-out:rw
      - ./out/sim.log:/app/devtools/data/31337/sim.log:rw
    environment:
      - PARTICIPANT_MNEMONIC=${PARTICIPANT_MNEMONIC}
    depends_on:
      anvil:
        condition: service_healthy

  indexer:
    image: ghcr.io/izcm/nft-indexer:v0.2.0
    ports:
      - "5000:5000" # http
      - "5001:5001" # websocket
    env_file: "./env.example/indexer.env" # static env
    environment: # dynamic env
      - FORK_START_BLOCK=${FORK_START_BLOCK}
    volumes: # chain config
      - ./chains.json:/app/chains.json:ro
    depends_on:
      anvil:
        condition: service_healthy
      mongo:
        condition: service_started

  frontend:
    image: frontend
    build:
      context: https://github.com/izcm/trading-terminal.git#v0.2.0
      args: # bundled at build time
        ANVIL_MARKETPLACE: ${MARKETPLACE_ADDR}
        INDEXER_API_CLIENT: http://${APP_HOST}:5000/api
        INDEXER_WS: ws://${APP_HOST}:5001
        MODE: DEMO # show pipeline progress bars + etc. demo elements and chain config
    env_file: "./env.example/frontend.env"
    ports:
      - "3000:3000"
    depends_on:
      - anvil
      - indexer

  setup:
    image: ghcr.io/foundry-rs/foundry
    user: ${UID}
    profiles: ["setup"]
    working_dir: /app
    entrypoint:
      - bash
      - -c
      - |
        bash /app/scripts/ensure-mnemonic.sh &&
        bash /app/scripts/pipeline-window.sh $SECONDS_AGO &&
        set -a && . /app/.env.runtime && set +a &&
        bash /app/scripts/determine-dmrkt-address.sh
    environment:
      - MNEMONIC_JSON=/app/config/sim/mnemonic.example.json
      - TOML=/app/config/sim/pipeline.toml
      - MAINNET_RPC=${MAINNET_RPC}
    volumes:
      # scripts
      - ./scripts:/app/scripts:ro

      # fork context config
      - ./config/sim:/app/config/sim:rw

      # environment files
      - ./env.example:/app/env.example:rw
      - ./.env.runtime:/app/.env.runtime:rw

      # supported chains
      - ./chains.json:/app/chains.json:rw
