name: dmrkt

services:
  # INFRA
  anvil:
    image: ghcr.io/foundry-rs/foundry
    entrypoint: ["anvil"]
    command:
      - --fork-url=${MAINNET_RPC}
      - --chain-id=31337
      - --host=0.0.0.0
      - --port=8545
      - --fork-block-number=${FORK_START_BLOCK}
      - --mnemonic=${PHRASE}
      - --accounts=10
      - --silent
    ports:
      - "8545:8545"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  # DMRKT COMPONENTS
  sim:
    image: ghcr.io/izcm/dmrkt-contracts:latest
    volumes:
      # config files + env
      - ./config/sim/mnemonic.example.json:/app/devtools/data/31337/mnemonic.json:rw
      - ./config/sim/pipeline.toml:/app/devtools/pipeline.toml:rw
      - ./env.example/sim.env:/app/devtools/.env:ro
      # broadcst logs
      - ./out/broadcast:/app/devtools/broadcast:rw
    depends_on:
      - anvil

  indexer:
    image: ghcr.io/izcm/dmrkt-indexer:latest
    ports:
      - "5000:5000" # http
      - "5001:5001" # websocket
    env_file: "./env.example/indexer.env" # static env
    environment: # dynamic env
      - FORK_START_BLOCK=${FORK_START_BLOCK}
    volumes: # chain config
      - ./chains.json:/app/chains.json:ro
    depends_on:
      - anvil
      - mongo

  frontend:
    image: frontend
    build:
      context: https://github.com/izcm/dmrkt-frontend.git
      args:
        NEXT_PUBLIC_MARKETPLACE_ADDR: ${MARKETPLACE_ADDR}
        NEXT_PUBLIC_ANVIL_RPC_URL: http://${APP_HOST}:8545
        NEXT_PUBLIC_INDEXER_API: http://${APP_HOST}:5000
        NEXT_PUBLIC_INDEXER_WS: ws://${APP_HOST}:5001
    env_file: "./env.example/frontend.env"
    ports:
      - "3000:3000"
    depends_on:
      - anvil
      - indexer

  setup:
    image: ghcr.io/foundry-rs/foundry
    user: ${UID}
    profiles: ["setup"]
    working_dir: /app
    entrypoint:
      - bash
      - -c
      - |
        bash /app/scripts/ensure-mnemonic.sh &&
        bash /app/scripts/pipeline-window.sh $SECONDS_AGO &&
        bash /app/scripts/determine-dmrkt-address.sh
    environment:
      - MNEMONIC_JSON=/app/config/sim/mnemonic.example.json
      - TOML=/app/config/sim/pipeline.toml
      - MAINNET_RPC=${MAINNET_RPC}
    volumes:
      # scripts
      - ./scripts:/app/scripts:ro

      # fork context config
      - ./config/sim:/app/config/sim:rw

      # environment files
      - ./env.example:/app/env.example:rw
      - ./.env.runtime:/app/.env.runtime:rw

      # supported chains
      - ./chains.json:/app/chains.json:rw
