# TODO: https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-registry/
name: dmrkt

services:
  # INFRA

  anvil:
    image: ghcr.io/foundry-rs/foundry
    entrypoint: ["anvil"]
    command:
      - --fork-url=${MAINNET_RPC}
      - --chain-id=31337
      - --host=0.0.0.0
      - --port=8545
      - --fork-block-number=${FORK_START_BLOCK}
      - --mnemonic=${PHRASE}
      - --accounts=10
      - --silent
    ports:
      - "8545:8545"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  # DMRKT COMPONENTS
  sim:
    image: sim
    # build:
    #   context: https://github.com/izcm/dmrkt-contracts.git
    volumes:
      - ./config/sim/mnemonic.example.json:/app/devtools/data/31337/mnemonic.json:rw
      - ./config/sim/pipeline.toml:/app/devtools/pipeline.toml:rw
      - ./env.example/sim.env:/app/devtools/.env:ro
    # depends_on:
    #   - anvil

  indexer:
    image: indexer
    #build:
    #  context: https://github.com/izcm/dmrkt-indexer.git
    ports:
      - "5000:5000" # http
      - "5001:5001" # websocket
    env_file: "./env.example/indexer.env"
    depends_on:
      - anvil
      - mongo

  frontend:
    image: frontend
    # build:
    #   context: https://github.com/izcm/dmrkt-frontend.git
    ports:
      - "3000:3000"
    env_file: "./env.example/frontend.env"
    depends_on:
      - anvil
      - indexer

  setup:
    image: ghcr.io/foundry-rs/foundry
    profiles: ["setup"]
    working_dir: /app
    user: root
    entrypoint:
      - bash
      - -c
      - |
        bash /app/scripts/pipeline-window.sh $SECONDS_AGO &&
        bash /app/scripts/determine-dmrkt-address.sh
    environment:
      - MNEMONIC_JSON=/app/config/sim/mnemonic.example.json
      - TOML=/app/config/sim/pipeline.toml
      - MAINNET_RPC=${MAINNET_RPC}
    volumes:
      - ./scripts/pipeline-window.sh:/app/scripts/pipeline-window.sh:ro
      - ./scripts/determine-dmrkt-address.sh:/app/scripts/determine-dmrkt-address.sh:ro
      - ./config/sim/mnemonic.example.json:/app/config/sim/mnemonic.example.json:ro
      - ./config/sim/pipeline.toml:/app/config/sim/pipeline.toml:rw
      - ./env.example:/app/env.example:rw
      - ./.env:/app/.env:rw
